### ISSUE TITLE
systemctl reload main-liquidsoap.service

### ISSUE THREAD

**Issue by pedro-nonfree** [savonet/liquidsoap-daemon#14]
Looks like I'm asking something impossible/inviable. A way to refresh script without cutting the stream, just rereading the configuration / conditions / state

I would like to maintain a weekly schedule for a radio in a static liquidsoap script inspired by "Time intervals" in http://liquidsoap.info/doc-dev/language.html

The (real) intention is "to implement" what there is in a ical.

I look the liquid soap scheduler from https://sourceforge.net/p/savonet/mailman/message/27603912/ but I think this is too much complicated (I prefer neat, simple thinks to make it easier maintenance; that includes airtime/libretime)

I'm open to another ways to do the same.

Sorry if this is not the place or if I'm mixing too much things. At least, there is an example where `reload` is useful

**Comment by pedro-nonfree** [comment]
I solved this creating another script that manages the fallbacks between live streams and the schedule streams (with also an extra blank stream). That way, I can refresh live streams and schedules and I don't loose the stream. In other words, the stream would be loose in hypotetical change of that fallback script, but that fallback script is not going to change because is very static and the changes are placed to the other scripts:

```
# src "Includes" http://savonet.sourceforge.net/doc-svn/language.html
%include "/home/liquidsoap/passwords.liq"

# thanks http://savonet.sourceforge.net/doc-svn/cookbook.html

live1 = input.http("http://example.com:8000/live1.mp3")
live2 = input.http("http://example.com:8000/live2.mp3")
schedule = input.http("http://example.com:8000/schedule.mp3")

# A simple cross-fade -> src "Switch-based transitions" http://savonet.sourceforge.net/doc-svn/cookbook.html
def crossfade(a,b)
  add(normalize=false,
      [ sequence([ blank(duration=1.),
                   fade.initial(duration=2.,b) ]),
        fade.final(duration=1.,a) ])
end

default_transition = [
  crossfade, # live1
  crossfade, # live2
  crossfade # schedule
]

signal = fallback(
  track_sensitive=false,
  transitions = default_transition,
  [
    live1,
    live2,
    schedule
  ])

output.icecast(%mp3,
     description = "take care of having always a fallback (at least runs silence)",
     password = icecast_passwd, mount = "main.mp3",
     mksafe(signal))
```

**Comment by toots** [comment]
Yeah that's the way to go :-)

**Comment by pedro-nonfree** [comment]
(I'm probably hijaking myself, hehe) The only downside is that I have not found a way to shutdown the liquidsoap script in fadeout; it just stops the signal. I tried with `on_shutdown` 

```
set("log.file", false)
mysound = sine()

def finish()
  fade.final(duration=1., mysound)
  system("sleep 2")
  print("finish")
end

on_shutdown(fun() -> finish())

out(mysound)
```
