### ISSUE TITLE
[wish] setup logrotate

### ISSUE THREAD

**Issue by ghost** [savonet/liquidsoap-daemon#15]
as this script is putting liquidsoap in production mode probably would be interesting to incorporate logrotate

for example, from my first liquidsoap production streaming it generated a 600 M logfile that made the server to complain about disk resources

http://savonet.sourceforge.net/doc-1.0.1/in_production.html

**Comment by toots** [comment]
That's a really good idea. I'll see what I can do. Meanwhile, feel free to submit a pull request if you have an idea how to do it.
