### ISSUE TITLE
unable to find liquidsoap_binary in your path

### ISSUE THREAD

**Issue by carrzkiss** [savonet/liquidsoap-daemon#16]
I have tested this on both. Windows 2016 Server and Ubuntu 18.04
And when I get to this point
./daemonize-liquidsoap.sh
I get the error: unable to find liquidsoap_binary in your path

Could someone please shed some light on this issue?

p.s.
I followed the instructions on this page, for installing and setting up Liquidsoap.
https://www.linuxjournal.com/content/creating-internet-radio-station-icecast-and-liquidsoap

**Comment by carrzkiss** [comment]
I was able to get this installed.
I used the [Ubuntu Software Center]
And using this command
apt:liquidsoap
(From the following link [liquidsoap-on-ubuntu](https://tutorialforlinux.com/2018/01/27/how-to-install-liquidsoap-on-ubuntu-18-04-bionic-gnulinux/) )

everything installed and I am now setting up liquidsoap on Ubuntu 18.04

Wayne

**Comment by toots** [comment]
Good to know, all the best with your radio projects!

**Comment by carrzkiss** [comment]
Thanks, Toots.
Now on to another issue.
I got that part working, now I am having issues with 
>> sudo systemctl status liquidsoap
Output >>Starting liquidsoap channels: no script found in /etc/liquidsoap
I put a script in there for testing, and it is not finding it. I ran 
>> Sudo chmod 777 /etc/liquidsoap/quinnliq.liq
On the file, and still no go.

Of the fun of learning something new.

**Comment by carrzkiss** [comment]
A reboot took care of it.
Once I rebooted the system, it picked up on the script.

All is good now.

**Comment by DasithEdirisinghe** [comment]
> I have tested this on both. Windows 2016 Server and Ubuntu 18.04 And when I get to this point ./daemonize-liquidsoap.sh I get the error: unable to find liquidsoap_binary in your path
> 
> Could someone please shed some light on this issue?
> 
> p.s. I followed the instructions on this page, for installing and setting up Liquidsoap. https://www.linuxjournal.com/content/creating-internet-radio-station-icecast-and-liquidsoap

Hi run the below command before running the ./daemonize-liquidsoap.sh
- `eval $(opam env)`

**Comment by carrzkiss** [comment]
Hey, Dasith.
This was from 2018.
Though your information is valid.

**Comment by DasithEdirisinghe** [comment]
> Hey, Dasith. This was from 2018. Though your information is valid.

Hi @carrzkiss . Yeah but I hope it might be helpful for anyone who faces the same issue.
