### ISSUE TITLE
Liquid Soap Daemon setup as non root user

### ISSUE THREAD

**Issue by davebowl** [savonet/liquidsoap-daemon#22]
So, I'm running a webserver, and trying to setup liquid soap as a daemon for a specific user, but that user doesn't have sudo access, I am accessing their directory as `sudo -u userinquestion` but I get asked for my sudo password. Can I modify the script to use sudo as a different user, say my primary user, and install the daemon for a user that way?

I wasn't sure if it was safe to modify the script in this way. The only thing that should be starting/installing scripts is the admin user with sudo access, so I can't figure out how I would daemonize it as a root user, via a non root user. 

I also tried doing it with my primary user, but it tries to run the script from that user's home directory, not the `cwd`.

**Comment by davebowl** [comment]
I realized I could use base_dir, please disregard. I thought that was for something else.

**Comment by toots** [comment]
Glad to hear! All the best with your project!
