### ISSUE TITLE
Logrotate config generator: issue with path and user/group specification

### ISSUE THREAD

**Issue by TraceOrdin** [savonet/liquidsoap-daemon#26]
Hello! I really appreciate this tool and the logrotate configuration that it includes. Recently I noticed the liquidsoap logs weren't rotating and after some investigation determined the following:

- the log directory [at the top of the logrotate config](https://github.com/savonet/liquidsoap-daemon/blob/master/liquidsoap.logrotate.in#L1) is coming through incorrectly as `/home/user/liquidsoap-daemon/log/liquidsoap/*.log` when it is actually automatically set up in `/home/user/liquidsoap-daemon/log/*.log`

- the [pid directory in the logrotate config](https://github.com/savonet/liquidsoap-daemon/blob/master/liquidsoap.logrotate.in#L9) is coming through incorrectly as `/home/user/liquidsoap-daemon/run/liquidsoap/*.pid` when it is actually automatically set up in `/home/user/liquidsoap-daemon/pid/*.pid`

- Once the path issue is resolved, logrotate throws the following error: `error: skipping "/home/user/liquidsoap-daemon/log/scriptA.liq-run.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.`.  Adding `su user user` (where user is my username) near the top of the config solved this for me

Initially I fixed these items directly in the logrotate config and wanted to mention them in this repo for the benefit of others. About to submit a PR with a proposed fix to the generator file and script :)

**Comment by Sakrecoer** [comment]
i have this issue as well... logrotate 3.14.0 ubuntu 20.04.1 server

I'm no good at scripting so i temporarily fixed it by adding copytruncate option, because since it doesn't restart, the log keeps writing in the moved file.

(sorry for the noise, i managed to mistakenly comment the PR first)

**Comment by TraceOrdin** [comment]
I found that in ubuntu 20.04/logrotate 3.14.0 had some additional issues due to:

- [security changes to start-stop-daemon](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=921557) make it fail if run as root when the pidfile has non-root write access on it
- the 'su' command in the logrotate script doesn't carry through to the running of start-stop-daemon so it's still running as root, which I think is a logrotate issue
- liquidsoap writes the pidfile with read/write access to everyone and I don't see an option for changing that anywhere in the config

Here's what I did to the logrotate file after it was generated as a workaround to get logs rotating, in particular:
- removing world writable permission from the pid file before running start-stop-daemon with `chmod o-w liq`, 
- and also explicitly running start-stop-daemon with `su user -c` and doing the variable interpolation in curly braces because the command needs to be in double quotes since it's a param of su

```
/home/user/liquidsoap-daemon/log/*.log {
  su user usergroup
  compress
  rotate 5
  size 900k
  missingok
  sharedscripts
  postrotate
    for liq in /home/user/liquidsoap-daemon/pid/*.pid ; do
      if test $liq != '/home/user/liquidsoap-daemon/pid/*.pid' ; then
        chmod o-w $liq
        su user -c "start-stop-daemon --stop --signal USR1 --quiet --pidfile ${liq}"
      fi
    done
  endscript
}
```

Longer term I think it would be really good for liquidsoap to not create the pid file as world writable, or maybe even have a 'perm' flag like output.file to customize the permissions. I guess that should be an issue on the main liquidsoap repo.

**Comment by TraceOrdin** [comment]
Note I closed that earlier PR because of concern that su directive might break things in older versions of Ubuntu/logrotate

**Comment by toots** [comment]
Thanks for this report and sorry for the late response. I have fixed the pid dir issue. The file mode creation might be a script issue as the default creation mode should be `0o640`. I have added the default value to the script settings to make it explicit.
