### ISSUE TITLE
Problem when it is a fully qualified name

### ISSUE THREAD

**Issue by ligi** [savonet/liquidsoap-daemon#30]
I get the following:

```
$ ./liquidsoap-daemon/daemonize-liquidsoap.sh /home/liquidsoap/radio/radio-pwinject.liq

./liquidsoap-daemon/daemonize-liquidsoap.sh: 100: cannot create /home/liquidsoap/liquidsoap-daemon/script//home/liquidsoap/radio/radio-pwinject.liq-run.liq: Directory nonexistent
./liquidsoap-daemon/daemonize-liquidsoap.sh: 108: cannot create /home/liquidsoap/liquidsoap-daemon/script//home/liquidsoap/radio/radio-pwinject.liq-run.liq: Directory nonexistent
./liquidsoap-daemon/daemonize-liquidsoap.sh: 118: cannot create /home/liquidsoap/liquidsoap-daemon/script//home/liquidsoap/radio/radio-pwinject.liq-run.liq: Directory nonexistent
```

it only works when I use the options with the script to start in the default liquidsoap-daemon/script/ - but documentation states absolute should also work

> A full path to an existing script file.

**Comment by hayden-t** [comment]
I have this problem too.

**Comment by hayden-t** [comment]
I was able to get my/the-old /etc/init.d/liquidsoap startup daemon script from the debian stretch package and it still works even though im running buster now

**Comment by toots** [comment]
Should be fixed now. Thanks for the report and sorry for the delay..
