### ISSUE TITLE
doesn't work with relative paths

### ISSUE THREAD

**Issue by mtrabelsi** [savonet/liquidsoap-daemon#4]
My installation structure :

```
marwen@vps:~/liquidsoap-daemon$ tree
.
├── daemonize-liquidsoap.sh
├── playlist.txt
├── liquidsoap.initd
├── liquidsoap.initd.in
├── liquidsoap.launchd.in
├── log
│   └── run.log
├── main.liq
├── pid
│   └── run.pid
├── README.md
└── run.liq
```

My  main.liq script : 

> output.icecast(%vorbis, host = "localhost", port = 8000, password = "hackme", mount = "feirouz.ogg", mksafe(playlist("playlist.txt")))

When running the Daemon, liquidsoap can't see the relative path of my playlist.txt : 
`2017/01/19 02:34:44 [request:3] Nonexistent file or ill-formed URI "playlist.txt"!`

_This doesn't happen if I use one-liner command ( without liquidsoap-daemon )_

the only way I succeeded with is to put the absolute path like the follows : 

`playlist("/home/mawen/liquidsoap-daemon/playlist.txt")
`

Which it's not very convenient, it's better to use relative path instead 

Is there anything we can do about this limitation?

Cheers

**Comment by toots** [comment]
Is your playlist file named `playlist.txt` or `feirouz-playlist.txt` ? The file listing has `feirouz-playlist.txt` but your script says `playlist.txt`..

**Comment by mtrabelsi** [comment]
Yes that's correct ! but I fogot to change the name in the tree ( just named it to **playlist.txt** for simplicity :) )
