### ISSUE TITLE
Does not work on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by AlReem** [savonet/liquidsoap-daemon#7]
I ran the script as instructed in the readme and it seems the run.liq file is not created while executing `init_system=systemd ./daemonize-liquidsoap.sh`.  I went through the logic in the shell script but there was no case handling for systemd.  At the end of the script the service file is created referring to `run.liq`.
Correct me if I am wrong.

**Comment by toots** [comment]
Thanks for reporting that. I'll be looking at it shortly.

**Comment by articobandurini** [comment]
initd works well though...

**Comment by toots** [comment]
I've just uploaded the `1.3.0` tarball. This is next on my list.

**Comment by toots** [comment]
Should be fixed with `0.2.0`. Package updated pushed with `opam`
