### ISSUE TITLE
How to generate run.pid file?

### ISSUE THREAD

**Issue by itibet** [savonet/liquidsoap-daemon#8]
Hi,
I've installed the script and I'm running liquidsoap daemon with `sudo service liquidsoap start`.
I need the pid file to be generated to keep track of the process, I expect it in `${HOME}/liquidsoap-daemon/pid/run.pid` but no file is created.
Thanks for any help.

**Comment by toots** [comment]
Fixed with `0.2.0`!

**Comment by itibet** [comment]
Thanks a lot!

**Comment by Sakrecoer** [comment]
I ran into this very error after pulling the latest changes from this repo. It used to work fine before the latest changes. systemd complains about missing pid file, and indeed the file is not created...
