### ISSUE TITLE
Running two liquidsoap instances as daemon

### ISSUE THREAD

**Issue by mylselgan** [savonet/liquidsoap-daemon#9]
Hi,
I need to run two liquidsoap instances as daemon and out put to two different icecast servers from same user how can I achieve this?
scenario:
Radio1.liq outputs to icecastserver.com:8000/radio1.ogg
Radio2.liq outputs to icecastserver.com:8002/radio2.ogg

Both radios runs under the same user, How can I start or stop these radios separately.

**Comment by toots** [comment]
Hi,

That's a great question. It is not currently possible. I'll see about adding this functionality soon.

**Comment by cbsiddharth** [comment]
@toots: @mylselgan has a valid use case. I put some time into it and have a working prototype.

**Changes Made:**
Install daemon with `./daemonize-liquidsoap.sh radio-name` (looks for radio-name.liq or defaults to main.liq). This creates a service `radio-name-liquidsoap.<init_type>`. Then use start/stop/restart those services as and when needed.

Let me know if you like it. I can send a PR for it.

**Comment by toots** [comment]
For sure, please do!

**Comment by mylselgan** [comment]
Tested with systemd and works as expected. Thanks @cbsiddharth and @toots

**Comment by toots** [comment]
Fixed by #10
